name: AEMET Alertas Update

on:
  schedule:
    # Ejecuta el script cada hora en punto
    - cron: "0 * * * *"
  workflow_dispatch:
    # Permite ejecutarlo manualmente desde GitHub

permissions:
  contents: write

jobs:
  update-aemet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Ejecutar script AEMET
        env:
          AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
        run: python scripts/update_aemet.py
        
      - name: Hacer Commit y Push de los cambios
        run: |
          git config --global user.name "GitHub Action AEMET"
          git config --global user.email "action@github.com"
          git add data/alertas_aemet.json
          # Solo hace commit si hay cambios en el archivo
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizar datos de AEMET automáticamente" && git push)
